import katex from 'katex'
import type { Logger } from 'pino'
import type {
  PublicationAssembly,
  PublicationInlineNode,
  PublicationNode
} from '../../shared/contracts/publication'
import { isMathSourceStructurallySafe } from './math-source-safety'

export interface LatexPublicationLoss {
  code:
    | 'bibliography_metadata_unavailable'
    | 'latex_table_span_fallback'
    | 'latex_verbatim_sanitized'
    | 'math_text_fallback'
    | 'mermaid_source_fallback'
  sectionId: string
  blockId: string
  message: string
}

export function renderLatexPublication(input: {
  assembly: PublicationAssembly
  assetRelativePath(assetId: string): string
  log?: Pick<Logger, 'info' | 'warn' | 'error'>
}): { tex: string; losses: LatexPublicationLoss[] } {
  if (!input.assembly.ready) {
    const err = new Error('Publication preflight contains blocking errors')
    input.log?.error(
      {
        event: 'manuscript.publication.latex_render.failed',
        err,
        findingCount: input.assembly.findings.length
      },
      'LaTeX publication preflight contains blocking errors'
    )
    throw err
  }
  const startedAt = Date.now()
  input.log?.info(
    {
      event: 'manuscript.publication.latex_render.started',
      nodeCount: input.assembly.nodes.length,
      pageSize: input.assembly.options.pageSize,
      template: input.assembly.options.template,
      includeTableOfContents: input.assembly.options.includeTableOfContents
    },
    'LaTeX publication render started'
  )
  try {
    const losses: LatexPublicationLoss[] = []
    const body = input.assembly.nodes.flatMap((node) => convertNode(node, input, losses))
    const firstTarget = input.assembly.nodes.find((node) => 'target' in node)?.target
    if (input.assembly.referenceCount > 0 && firstTarget !== undefined) {
      losses.push({
        code: 'bibliography_metadata_unavailable',
        sectionId: firstTarget.sectionId,
        blockId: firstTarget.blockId ?? 'section',
        message:
          'References were emitted as readable numbered entries because structured BibTeX metadata is unavailable.'
      })
    }
    const options = input.assembly.options
    const lines = [
      '% Generated by WriteLLM. Target engine: XeLaTeX.',
      `% Publication source hash: ${input.assembly.sourceHash}`,
      `% Template profile: ${options.template}`,
      `\\documentclass[UTF8,${options.pageSize === 'A4' ? 'a4paper' : 'letterpaper'}]{ctexart}`,
      '\\usepackage{geometry}',
      `\\geometry{top=${options.marginsMm.top}mm,right=${options.marginsMm.right}mm,bottom=${options.marginsMm.bottom}mm,left=${options.marginsMm.left}mm}`,
      '\\usepackage{graphicx}',
      '\\usepackage{booktabs}',
      '\\usepackage{longtable}',
      '\\usepackage{enumitem}',
      '\\usepackage{listings}',
      '\\usepackage{caption}',
      '\\usepackage{amssymb}',
      '\\usepackage[normalem]{ulem}',
      '\\usepackage[hidelinks,unicode]{hyperref}',
      '\\graphicspath{{assets/}}',
      '\\setlist{nosep}',
      `\\title{${escapeLatex(input.assembly.title)}}`,
      '\\author{WriteLLM}',
      '\\date{}',
      '\\begin{document}',
      '\\maketitle',
      ...(options.includeTableOfContents ? ['\\tableofcontents', '\\clearpage'] : []),
      ...body,
      '\\end{document}',
      ''
    ]
    const tex = lines.join('\n')
    input.log?.info(
      {
        event: 'manuscript.publication.latex_render.completed',
        byteSize: Buffer.byteLength(tex),
        lossCount: losses.length,
        lossesByCode: countLossesByCode(losses),
        durationMs: Date.now() - startedAt
      },
      'LaTeX publication render completed'
    )
    return { tex, losses }
  } catch (err) {
    input.log?.error(
      {
        event: 'manuscript.publication.latex_render.failed',
        err,
        durationMs: Date.now() - startedAt
      },
      'LaTeX publication render failed'
    )
    throw err
  }
}

function countLossesByCode(losses: readonly LatexPublicationLoss[]): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const loss of losses) counts[loss.code] = (counts[loss.code] ?? 0) + 1
  return counts
}

function convertNode(
  node: PublicationNode,
  input: {
    assembly: PublicationAssembly
    assetRelativePath(assetId: string): string
  },
  losses: LatexPublicationLoss[]
): string[] {
  switch (node.type) {
    case 'heading':
      return [
        `\\${headingCommand(node.level)}{${inlineLatex(node.content, node.target, losses)}}`,
        `\\label{${safeLabel('sec', node.target.sectionId, node.target.blockId)}}`,
        ''
      ]
    case 'paragraph':
      return [inlineLatex(node.content, node.target, losses), '']
    case 'list_item': {
      const environment = node.kind === 'numbered' ? 'enumerate' : 'itemize'
      const marker =
        node.kind === 'check' ? `[${node.checked ? '$\\boxtimes$' : '$\\square$'}] ` : ''
      return [
        `\\begin{${environment}}`,
        `  \\item ${marker}${inlineLatex(node.content, node.target, losses)}`,
        `\\end{${environment}}`,
        ''
      ]
    }
    case 'quote':
      return ['\\begin{quote}', inlineLatex(node.content, node.target, losses), '\\end{quote}', '']
    case 'code': {
      const content = safeListing(node.content)
      if (content.changed) recordListingLoss(node, losses)
      return [
        `\\begin{lstlisting}${node.language === '' ? '' : `[language=${safeListingOption(node.language)}]`}`,
        content.value,
        '\\end{lstlisting}',
        ''
      ]
    }
    case 'table': {
      const columns = Math.max(1, ...node.rows.map((row) => row.length))
      const lines = [`\\begin{longtable}{${'l'.repeat(columns)}}`, '\\toprule']
      node.rows.forEach((row, rowIndex) => {
        lines.push(
          `${row
            .map((cell) => {
              if (cell.rowspan > 1) {
                losses.push({
                  code: 'latex_table_span_fallback',
                  sectionId: node.target.sectionId,
                  blockId: node.target.blockId ?? '',
                  message: 'A row-spanning table cell was emitted without its row span.'
                })
              }
              const content = inlineLatex(cell.content, node.target, losses)
              return cell.colspan > 1 ? `\\multicolumn{${cell.colspan}}{l}{${content}}` : content
            })
            .join(' & ')} \\\\`
        )
        if (rowIndex + 1 === node.headerRows) lines.push('\\midrule')
      })
      lines.push('\\bottomrule', '\\end{longtable}', '')
      return lines
    }
    case 'figure':
      return [
        '\\begin{figure}[htbp]',
        '  \\centering',
        `  \\includegraphics[width=\\linewidth,height=0.75\\textheight,keepaspectratio]{\\detokenize{${input.assetRelativePath(node.assetId)}}}`,
        `  \\caption{${escapeLatex(node.caption)}}`,
        `  \\label{${safeLabel('fig', node.figureId, null)}}`,
        `  % Alternative text: ${escapeComment(node.altText)}`,
        '\\end{figure}',
        ''
      ]
    case 'math':
      if (safeMath(node.source)) {
        return ['\\[', node.source, '\\]', ...(node.caption ? [escapeLatex(node.caption)] : []), '']
      }
      losses.push({
        code: 'math_text_fallback',
        sectionId: node.target.sectionId,
        blockId: node.target.blockId ?? '',
        message: 'Unsafe or unsupported formula source was emitted as readable text.'
      })
      return [`\\texttt{${escapeLatex(node.source)}}`, '']
    case 'mermaid': {
      const content = safeListing(node.source)
      if (content.changed) recordListingLoss(node, losses)
      losses.push({
        code: 'mermaid_source_fallback',
        sectionId: node.target.sectionId,
        blockId: node.target.blockId ?? '',
        message: 'Mermaid was retained as source listing in the LaTeX project.'
      })
      return [
        ...(node.caption ? [`\\paragraph{${escapeLatex(node.caption)}}`] : []),
        '\\begin{lstlisting}',
        content.value,
        '\\end{lstlisting}',
        ''
      ]
    }
    case 'references':
      return [
        '\\section*{References}',
        '\\addcontentsline{toc}{section}{References}',
        '\\begin{enumerate}[label={[\\arabic*]}]',
        ...node.entries.map((entry) => `  \\item ${escapeLatex(entry.title)}`),
        '\\end{enumerate}',
        ''
      ]
  }
}

function inlineLatex(
  nodes: PublicationInlineNode[],
  target: { sectionId: string; blockId: string | null },
  losses: LatexPublicationLoss[]
): string {
  return nodes
    .map((node) => {
      if (node.type === 'citation') return `\\textsuperscript{[${node.number}]}`
      if (node.type === 'link') {
        return `\\href{${escapeUrl(node.href)}}{${node.children.map(styledText).join('')}}`
      }
      if (node.type === 'math') {
        if (safeMath(node.source, false)) return `\\(${node.source}\\)`
        losses.push({
          code: 'math_text_fallback',
          sectionId: target.sectionId,
          blockId: target.blockId ?? '',
          message: 'Unsafe or unsupported inline formula source was emitted as readable text.'
        })
        return `\\texttt{${escapeLatex(`$${node.source}$`)}}`
      }
      return styledText(node)
    })
    .join('')
}

function styledText(node: {
  text: string
  style: { bold: boolean; italic: boolean; underline: boolean; strike: boolean; code: boolean }
}): string {
  let result = escapeLatex(node.text)
  if (node.style.code) result = `\\texttt{${result}}`
  if (node.style.strike) result = `\\sout{${result}}`
  if (node.style.underline) result = `\\underline{${result}}`
  if (node.style.italic) result = `\\emph{${result}}`
  if (node.style.bold) result = `\\textbf{${result}}`
  return result
}

export function escapeLatex(value: string): string {
  const replacements: Record<string, string> = {
    '\\': '\\textbackslash{}',
    '{': '\\{',
    '}': '\\}',
    '#': '\\#',
    $: '\\$',
    '%': '\\%',
    '&': '\\&',
    _: '\\_',
    '^': '\\textasciicircum{}',
    '~': '\\textasciitilde{}'
  }
  return value.replace(/[\\{}#$%&_^~]/gu, (character) => replacements[character] ?? character)
}

function escapeUrl(value: string): string {
  return value
    .replaceAll('\\', '%5C')
    .replaceAll('{', '%7B')
    .replaceAll('}', '%7D')
    .replaceAll('%', '\\%')
    .replaceAll('#', '\\#')
}

function escapeComment(value: string): string {
  return value.replace(/[\r\n]+/gu, ' ').replaceAll('%', '\\%')
}

function headingCommand(level: number): string {
  return ['section', 'subsection', 'subsubsection', 'paragraph', 'subparagraph'][
    Math.min(level, 5) - 1
  ] as string
}

function safeLabel(prefix: string, first: string, second: string | null): string {
  const value = `${first}-${second ?? ''}`.replace(/[^A-Za-z0-9.-]/gu, '-').slice(0, 96)
  return `${prefix}:${value}`
}

function safeListing(value: string): { value: string; changed: boolean } {
  const safe = value.replace(/\\end\s*\{\s*lstlisting\s*\}/giu, '＼end{lstlisting}')
  return { value: safe, changed: safe !== value }
}

function safeListingOption(value: string): string {
  return value.replace(/[^A-Za-z0-9_+-]/gu, '').slice(0, 32)
}

function recordListingLoss(
  node: Extract<PublicationNode, { type: 'code' | 'mermaid' }>,
  losses: LatexPublicationLoss[]
): void {
  losses.push({
    code: 'latex_verbatim_sanitized',
    sectionId: node.target.sectionId,
    blockId: node.target.blockId ?? '',
    message: 'A listing terminator was neutralized to preserve the generated document boundary.'
  })
}

function safeMath(source: string, displayMode = true): boolean {
  if (!isMathSourceStructurallySafe(source)) return false
  return !katex
    .renderToString(source, {
      displayMode,
      output: 'mathml',
      throwOnError: false,
      strict: 'ignore',
      trust: false,
      maxExpand: 1_000,
      maxSize: 50
    })
    .includes('katex-error')
}
